#!/usr/bin/env bash
# command to install nginx in my web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx config
sudo nginx -t

# reloading my web server to see the updated changes
sudo service nginx reload
